COMMAND_IDENTIFY = 0
COMMAND_CAMERA_STREAM = 3
COMMAND_CAMERA_STREAM_OFF_ONN = 5 # Składa się z dwóch bajtów COMMAND_CAMERA_STREAM_OFF_ONN i boola
COMMAND_CAMERA_MOVE_DETECTED = 6 # Składa się z jednego bajta COMMAND_CAMERA_MOVE_DETECTED
COMMAND_CAMERA_MOVE_DETECTED_OFF_ONN = 7 # Składa się z jednego bajta COMMAND_CAMERA_MOVE_DETECTED_OFF_ONN i boola